# yaml-language-server: $schema=https://taskfile.dev/schema.json

version: "3"

vars:
  SRC: unixtcp.c

tasks:
  default:
    cmds:
      - "{{.TASK_EXE}} -l"
    silent: true

  build:darwin:
    desc: build for mac
    vars:
      BASE:
        sh: basename {{.SRC}} .c
      EXT: .dylib
    cmds:
      - clang -O3 -Wall -o {{.BASE}}{{.EXT}} -dynamiclib {{.SRC}}
      - clang -O3 -DDEBUG -Wall -o {{.BASE}}-debug{{.EXT}} -dynamiclib {{.SRC}}

  run:darwin:
    desc: run for mac
    vars:
      BASE:
        sh: basename {{.SRC}} .c
      EXT: .dylib
    requires:
      vars:
        - PORT
        - NAME
    cmds:
      - echo "does not work..."
      - env DYLD_FORCE_FLAT_NAMESPACE=1 DYLD_INSERT_LIBRARIES=./{{.BASE}}{{.EXT}} SOCKUNIX_PORT={{.PORT}} SOCKUNIX_PATH={{.NAME}} {{.CLI_ARGS}}

  build:linux:
    desc: build for linux
    vars:
      BASE:
        sh: basename {{.SRC}} .c
      EXT: .so
    cmds:
      - gcc -O3 -Wall -o {{.BASE}}{{.EXT}} -shared {{.SRC}}
      - gcc -O3 -Wall -DDEBUG -o {{.BASE}}-debug{{.EXT}} -shared {{.SRC}}

  run:linux:
    desc: run for linux
    vars:
      BASE:
        sh: basename {{.SRC}} .c
      EXT: .so
    requires:
      vars:
        - PORT
        - NAME
    cmds:
      - env LD_PRELOAD=./{{.BASE}}{{.EXT}} SOCKUNIX_PORT={{.PORT}} SOCKUNIX_PATH={{.NAME}} {{.CLI_ARGS}}

  build:
    desc: build
    cmds:
      - task: build:{{OS}}

  run:
    desc: run
    cmds:
      - task: run:{{OS}}

  clean:
    desc: cleanup
    cmds:
      - rm -rf *.so *.dylib
